# Generated by Django 2.1.3 on 2018-11-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_add_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentservice',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='final_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='original_price',
            field=models.IntegerField(default=0),
        ),
    ]
