# Generated by Django 2.1.3 on 2018-11-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_appointment_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='tip',
            field=models.IntegerField(default=0),
        ),
    ]
