# Generated by Django 2.1.3 on 2018-11-06 07:46

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_appointment_tip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
