# Generated by Django 2.1.3 on 2018-11-08 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_auto_20181106_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='has_free_retouch',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
    ]
